from lista_ligada import DoubleLinkedList

l = DoubleLinkedList()
print(f"L esta vacia? {l.is_empty()}")
x = l.get_size()
print(x)
l.append(3)
print(f"L esta vacia? {l.is_empty()} ")
l.append(5)
l.append(6)
l.append(20)
l.append(25)
x = l.get_size()
print(x)
l.reverse_transversal()
a = l.find_from_tail(25)
print(a)
b = l.find_from_head(30)
print(b)
"""
l.remove_from_tail(25)
l.transversal()
l.reverse_transversal()
c = l.get_size()
print(c)

l.remove_from_tail(6)
l.reverse_transversal()
c = l.get_size()
print(c)

l.remove_from_tail(22)
l.reverse_transversal()
print("--------------------------------------")
l.transversal()
c = l.get_size()
print(c)
"""
l.remove_from_head(25)
l.transversal()
print("--------------------------------------")
l.reverse_transversal()
c = l.get_size()
print(c)
