from lista_circular import CircularList

l = CircularList()
print(f"la lista esta vacia? {l.is_empty()}")
l.insert(40)
#l.transversal()
print(f"la lista esta vacia? {l.is_empty()}")
l.insert(55)
#l.transversal()
l.insert(30)
#l.transversal()
l.insert(35)
#l.transversal()
l.insert(44)
#l.transversal()
l.insert(25)
#l.transversal()
l.insert(33)
l.insert(40)
#l.transversal()
l.insert(38)
#l.transversal()
l.insert(60)
#l.transversal()
l.insert(63)
#l.transversal()
l.insert(24)
#l.transversal()
l.insert(43)
#l.transversal()
l.insert(70)
#l.transversal()
x = l.search(40)
print(x)
l.remove(25)
l.remove(70)
l.remove(38)
l.remove(24)
l.transversal()
l.remove(80)
