from listas import LinkedList

l = LinkedList()
print(f"L esta vacia? {l.is_empty()}")
l.append(10)
l.append(5)
l.append(6)
l.append(20)
l.append(25)
print(f"L esta vacia? {l.is_empty()}")
l.tranversal()
l.remove(10)
l.tranversal()
l.preppend(3)
l.tranversal()
x = l.tail()
print(x.data)
print(l.get(1))
l.Add_before(6,8)
l.tranversal()
l.Add_after(6,12)
l.tranversal()
